#!/bin/sh
echo $* > $0.log
set >> > $0.log

. colors

DRV_VERS=`nvidia-smi --help | head -n 1 | awk '{print $NF}' | sed 's/v//' | tr '.' ' ' | awk '{print $1}'`

version_dir="/hive/custom/${CUSTOM_NAME}/$(CUSTOM_VERSION)"

if [ ${DRV_VERS} -ge 396 ]; then
   cudaver="9.2"
   exesuffix="zjazz_cuda${cudaver}_linux/zjazz_cuda"
   echo -e "(${BCYAN}CUDA ${cudaver}${NOCOLOR} compatible)"
   minerexe="${version_dir}/${exesuffix}"
else
   cudaver="9.1"
   exesuffix="zjazz_cuda${cudaver}_linux/zjazz_cuda"
   echo -e "(${BCYAN}CUDA ${cudaver}${NOCOLOR} compatible)"
   minerexe="${version_dir}/${exesuffix}"
fi

miner_archive="zjazz_cuda${cudaver}_linux_suqa_0.991.tar.gz"
miner_url="https://github.com/zjazz/zjazz_cuda_miner_experimental/releases/download/x22i_0991/$(miner_archive)"

download_n_unpack(){
   mkdir -p "${version_dir}" > /dev/null 2>&1
   if [ -d "${version_dir}" ]; then
      echo "${RED}Unable to create version working directory: "${version_dir}" ${NOCOLOR}"
      exit 1
   fi

   cd "${version_dir}"
   echo "Downloading $(miner_archive)..."
   rm "$exesuffix" > /dev/null 2>&1
   curl -o "${miner_archive}" "{$miner_url}"
   if [ $? -ne 0 ]; then
      echo "Failed to download miner from ${miner_url}"
      exit 1
   fi
   echo Done.
   echo "Unpacking $(miner_archive)..."
   tar xvzf "$(miner_archive)" "$exesuffix"
   if [ $? -ne 0 ]; then
      echo "Failed to unpack miner archive from ${miner_archive}"
      exit 1
   fi
   echo Done.
}

if [ -x "$minerexe"]; then
   "$minerexe" $*
else
   echo Unable to run miner
fi

